/* Regularización Echo integrada en Panel de Operaciones */
let REG={residentes:[],convenios:[],filtro:'deuda',q:''};
const REG_CUOTA=515;
function regMeses(r){return Array.isArray(r.meses_debe)?r.meses_debe.length:Number(r.meses_debe||0)}
function regHist(r){return Math.max(0,Number(r.adeudo||0))}
function regTel(r){return String(r.telefono||'').replace(/\D/g,'')}
function regWaTel(r){let n=regTel(r);if(n.length===10)n='52'+n;return n}
function regActivo(r){return REG.convenios.find(c=>String(c.estado||'').toLowerCase()==='activo'&&(Number(c.id_residente)===Number(r.id_residente)||String(c.ident||'')===String(r.ident||'')))}
function regDesc(m){return m>=13?20:m>=7?10:0}
function regPlanes(r){const h=regHist(r),m=regMeses(r),d=regDesc(m),net=h*(1-d/100);return [3,6,12].map(t=>({meses:t,nombre:t===3?'Echo Rápido':t===6?'Echo Regulariza':'Echo Flexible',descuentoPct:d,descuentoMonto:h-net,adeudoConDescuento:net,abono:net/t,totalMensual:net/t+REG_CUOTA,totalQuincenal:(net/t+REG_CUOTA)/2,recomendado:(m>=13?t===12:m>=7?t===6:t===3)}))}
function regBadge(d){return d===20?'p-warn':d===10?'p-amb':'p-blue'}
async function vRegularizacion(){
  const [dir,conv]=await Promise.all([rpc('pg_directorio',C),rpc('pg_convenios_pago',C)]);
  REG.residentes=(dir&&dir.residentes)||[]; REG.convenios=(conv&&conv.convenios)||[];
  renderRegularizacion();
}
function renderRegularizacion(){
  let rows=REG.residentes.filter(r=>regHist(r)>0||regActivo(r));
  const q=(REG.q||'').toLowerCase().trim();
  if(q)rows=rows.filter(r=>[r.ident,r.nombre_completo,r.telefono].some(v=>String(v||'').toLowerCase().includes(q)));
  rows=rows.filter(r=>{const a=regActivo(r),m=regMeses(r),d=regDesc(m),f=REG.filtro;if(f==='activo')return !!a;if(a)return false;if(f==='20')return d===20;if(f==='10')return d===10;if(f==='corto')return m>=3&&m<=6;if(f==='sin_tel')return !regTel(r);return regHist(r)>0});
  rows.sort((a,b)=>regMeses(b)-regMeses(a)||regHist(b)-regHist(a));
  const deuda=REG.residentes.filter(r=>regHist(r)>0).length, contactables=REG.residentes.filter(r=>regHist(r)>0&&regTel(r)).length, cartera=REG.residentes.reduce((s,r)=>s+regHist(r),0), activos=REG.residentes.filter(regActivo).length;
  $('vista').innerHTML=`
    <div class="card" style="background:linear-gradient(135deg,#EEF3FF,#fff);border-color:#B8CCFF">
      <div class="chead"><div><h2>💬 Regularización Echo</h2><p class="sub">Paga el presente + arregla el pasado · gestión directa desde el panel de Rosaura</p></div></div>
      <div class="kpis"><div class="kpi"><div class="l">Con adeudo</div><div class="v">${deuda}</div></div><div class="kpi"><div class="l">Contactables</div><div class="v">${contactables}</div></div><div class="kpi"><div class="l">Cartera histórica</div><div class="v">${money(cartera)}</div></div><div class="kpi"><div class="l">Convenios activos</div><div class="v">${activos}</div></div></div>
    </div>
    <div class="card tight"><div class="grid g2"><div><label>Buscar residente</label><input id="regQ" placeholder="Unidad, nombre o teléfono" value="${esc(REG.q||'')}"></div><div><label>Segmento</label><select id="regF"><option value="deuda">Todos con adeudo</option><option value="20">20% beneficio</option><option value="10">10% beneficio</option><option value="corto">3–6 meses</option><option value="activo">Convenio activo</option><option value="sin_tel">Sin teléfono</option></select></div></div></div>
    <div id="regList">${rows.length?rows.slice(0,120).map(regCard).join(''):'<div class="card empty"><div class="t">Sin residentes para este filtro.</div></div>'}</div>`;
  $('regF').value=REG.filtro;$('regF').onchange=e=>{REG.filtro=e.target.value;renderRegularizacion()};$('regQ').oninput=e=>{REG.q=e.target.value;renderRegularizacion()};
  document.querySelectorAll('[data-reg-offer]').forEach(b=>b.onclick=()=>regOpenOffer(Number(b.dataset.regOffer)));
  document.querySelectorAll('[data-reg-active]').forEach(b=>b.onclick=()=>regOpenActive(Number(b.dataset.regActive)));
}
function regCard(r){const a=regActivo(r),m=regMeses(r),d=regDesc(m),p=regPlanes(r).find(x=>x.recomendado)||regPlanes(r)[1];return `<div class="item"><div class="ihead"><div class="iname">${esc(r.ident||'')} · ${esc(r.nombre_completo||'')}</div>${a?'<span class="pill p-ok">Convenio activo</span>':`<span class="pill ${regBadge(d)}">${d?d+'% beneficio':'Sin descuento'}</span>`}</div><div class="dl"><div><b>Teléfono</b><span>${esc(r.telefono||'Sin teléfono')}</span></div><div><b>Meses</b><span>${m}</span></div><div><b>Adeudo</b><span>${money(regHist(r))}</span></div><div><b>Plan</b><span>${a?'Vigente':p.nombre+' · '+p.meses+' meses'}</span></div><div><b>Desde</b><span>${a?money(a.abono_mensual):money(p.totalMensual)}/mes</span></div></div><div class="acts">${a?`<button class="btn gh sm" data-reg-active="${r.id_residente}">Ver convenio activo</button>`:`<button class="btn sm" data-reg-offer="${r.id_residente}">💬 Preparar WhatsApp</button>`}</div></div>`}
function regOpenActive(id){const r=REG.residentes.find(x=>Number(x.id_residente)===id),a=r&&regActivo(r);if(!a)return;$('sheetBox').innerHTML=`<div class="chead"><h2>${esc(r.ident)} · Convenio activo</h2><span class="pill p-ok">Activo</span></div><div class="grid g2"><div class="kpi"><div class="l">Monto acordado</div><div class="v">${money(a.monto_total)}</div></div><div class="kpi"><div class="l">Abono mensual</div><div class="v">${money(a.abono_mensual)}</div></div><div class="kpi"><div class="l">Saldo convenio</div><div class="v">${money(a.saldo_convenio)}</div></div><div class="kpi"><div class="l">Próximo pago</div><div class="v" style="font-size:1rem">${esc(a.proximo_pago||'—')}</div></div></div><div class="acts"><button class="btn gh" onclick="cerrarSheet()">Cerrar</button></div>`;$('sheet').classList.add('on')}
function regOpenOffer(id){const r=REG.residentes.find(x=>Number(x.id_residente)===id);if(!r)return;const ps=regPlanes(r),d=ps[0].descuentoPct;$('sheetBox').innerHTML=`<div class="chead"><h2>${esc(r.ident)} · Regularización</h2><span class="pill ${regBadge(d)}">${d?d+'% beneficio':'Sin descuento'}</span></div><p class="sub">${esc(r.nombre_completo)} · ${regMeses(r)} meses vencidos</p><div class="grid g3"><div class="kpi"><div class="l">Adeudo histórico</div><div class="v">${money(regHist(r))}</div></div><div class="kpi"><div class="l">Beneficio</div><div class="v">${money(ps[0].descuentoMonto)}</div></div><div class="kpi"><div class="l">Saldo regularizado</div><div class="v">${money(ps[0].adeudoConDescuento)}</div></div></div><div class="grid g3" style="margin-top:12px">${ps.map(p=>`<div class="card tight" style="${p.recomendado?'border:2px solid var(--blue)':''}"><h3>${p.nombre}${p.recomendado?' ⭐':''}</h3><div class="num" style="font-size:1.35rem;font-weight:800;color:var(--blue);margin:6px 0">${money(p.totalMensual)}/mes</div><div class="sub">${money(p.totalQuincenal)} quincenal · incluye $515 corriente</div><button class="btn wide" style="margin-top:10px" onclick="regSendOffer(${r.id_residente},${p.meses})">Enviar por WhatsApp</button></div>`).join('')}</div><div class="acts"><button class="btn gh" onclick="cerrarSheet()">Cerrar</button></div>`;$('sheet').classList.add('on')}
function regMensaje(r,p){const nombre=String(r.nombre_completo||'').split(' ')[0]||'Hola';return `Hola ${nombre}, somos Echo Administración de Manzana 80. Queremos apoyarte a regularizar tu cuenta de la unidad ${r.ident}.\n\nTu adeudo histórico es de ${money(regHist(r))}.${p.descuentoPct?` Por su antigüedad, cuentas con un beneficio de regularización del ${p.descuentoPct}%, por lo que el saldo elegible queda en ${money(p.adeudoConDescuento)}.`:''}\n\nLa opción ${p.nombre} es de ${money(p.totalMensual)} al mes, incluyendo tu cuota corriente de ${money(REG_CUOTA)}. También equivale a ${money(p.totalQuincenal)} por quincena.\n\nSi deseas regularizarte con esta opción, responde a este mensaje y te apoyamos con el siguiente paso.`}
async function regSendOffer(id,term){const r=REG.residentes.find(x=>Number(x.id_residente)===Number(id));if(!r)return;const p=regPlanes(r).find(x=>x.meses===Number(term)),n=regWaTel(r);if(!n){toast('Este residente no tiene teléfono','err');return}try{await rpc('pg_registrar_oferta_regularizacion',{...C,p_id_residente:r.id_residente,p_plan:p.nombre,p_plazo_meses:p.meses,p_meses_vencidos:regMeses(r),p_saldo_historico:regHist(r),p_descuento_pct:p.descuentoPct,p_descuento_monto:p.descuentoMonto,p_saldo_regularizado:p.adeudoConDescuento,p_cuota_corriente:REG_CUOTA,p_abono_deuda:p.abono,p_total_mensual:p.totalMensual,p_total_quincenal:p.totalQuincenal,p_canal:'whatsapp',p_notas:'Oferta preparada desde Panel de Operaciones'});}catch(e){}try{await rpc('pg_crear_llamada',{...C,p_id_residente:r.id_residente,p_asunto:'Regularización de cartera',p_descripcion:`Oferta ${p.nombre} ${p.meses} meses preparada por WhatsApp`,p_origen:'whatsapp'});}catch(e){}window.open(`https://wa.me/${n}?text=${encodeURIComponent(regMensaje(r,p))}`,'_blank');toast('WhatsApp preparado','good');cerrarSheet()}
